### PR TITLE
Add simple fix to handle multiple listeners for the same event

### PR DESCRIPTION
**Pull request by ManuW**
See issue #64

### CODE REVIEW

**Comment by acrisci** [comment]
Adding multiple listeners to an event must be supported by the library.

**Comment by ManuW** [comment]
I tested this and this works not as expected. If I add three listeners to my signal _test_, then every listeners receives three times the same signal instead of only once. See example code in issue #64.

**Comment by acrisci** [comment]
The fix is a bit more complicated than this. I'm working on this in #66 now.

**Comment by ManuW** [comment]
Okay. Thanks!

**Pull request closed without merging**
