### PR TITLE
updated proxy-object

### PR DESCRIPTION
**Pull request by leonardo-k**
add removeEventListeners function , it remove the internal library's listeners
it can remove a specific listener or all the listener of this proxy-object

### CODE REVIEW

**Comment by acrisci** [comment]
This is a good idea, and we may end up going this route. But can we do better?

Do you not have any listeners in your code at all? Maybe it would be better to not connect any listeners until a user connects them himself. And then a function like this could disconnect them. Or better yet, just use the standard EventEmitter `.off()` for that which would be very intuitive.

**Comment by leonardo-k** [comment]
have you seen these changes ? what do you think of it?

**Comment by acrisci** [comment]
I think this could be fixed without adding anything to the public api and if it can, that approach should be preferred. I'd like to do it that way and then see if this is still necessary.

I'd prefer if the object didn't have any listeners on the bus unless a user explicitly adds them with `on()` and if the user removes them all with `off()` the object will have no event listeners and can be cleaned up by garbage collection. That solves the problem in a more general way.

**Comment by acrisci** [comment]
The listeners are being added to the bus in a loop on object creation like this:

https://github.com/dbusjs/node-dbus-next/blob/62e9e265729f99182856cd76e62ef7db3d42dcef/lib/client/proxy-object.js#L110-L127

This is a bad approach because it leads to the memory leak in #29. Signals listeners are automatically added to the bus whether they are used or not and cannot be removed by the user.

Instead, these signals should not be added here. They should be added on demand as needed when listeners are added and removed from the interface.

There are events on the interface called `newListener` and `removeListener` that can be used for this purpose.

The interface can listen to these signals and whenever a listener is added, we can ensure that the appropriate listener for bus signals is in place. Whenever a listener is removed, we can ensure that there is no listener for bus signals in place.

Then you can use the normal EventEmitter functions to control the listeners on the bus in the expected way instead of adding this to the public api for the object.

**Comment by acrisci** [comment]
I've implemented the above in bd08f64.

**Comment by acrisci** [comment]
Ok I'm going to prefer the present solution. Thanks for bringing this to my attention and proposing a solution.

**Pull request closed without merging**
